name: Checks

on: [push, pull_request]

jobs:
  check_repository_cleanliness:
    name: Check Repository Cleanliness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check unwanted files & folders
        run: |
          declare -a patterns=(
            '#*#'
            '*-'
            '*.tmp'
            '*.o'
            '*.a'
            '*.so'
            '*.gcno'
            '*.gcda'
            '*.gcov'
            'CMakeCache.txt'
            '*.cmake'
            'CMakeFiles'
            '*.log'
            'tmp'
            'vcpkg'
          )

          found=0
          for pattern in "${patterns[@]}"; do
            if [[ -d "$pattern" || -f "$pattern" ]]; then
              find . -name "$pattern" | while read -r FILE; do
                echo "::error title=Unwanted file detected,file=$FILE::$FILE"
                found=1
              done
            fi
          done

          if [[ $found -eq 1 ]]; then
            exit 1
          fi

  check_program_compilation_linux:
    name: Check Program Compilation (Linux)
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - name: Compile Program
        run: |
          make
    
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          make
          make test

