name: Run Gomoku

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update apt-get
        run: |
          sudo apt-get update

      - name: Curl Static Bin
        run: |
          curl -L -o liskvork https://cdn.kreog.com/s/Nt7ayTXWctGkn6i/download/liskvork

      - name: add permission
        run: |
          sudo chmod +x liskvork

    #   - name: Build Liskvork
    #     run: |
    #       cd liskvork-0.1.1
    #       cmake .
    #       make
    #       cd ..
    #       ls

      - name: Build pbrain-gomoku-ai
        run: |
            make

      - name: Help liskvork
        run: |
            ./liskvork -h
        
      - name: Run ai
        run: |
            ls
            ./liskvork --player1-exe ./build/pbrain-gomoku-ai --player2-exe ./build/pbrain-gomoku-ai
          
          
