name: Run Gomoku

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update apt-get
        run: |
          sudo apt-get update

      - name: Curl Static Bin
        run: |
          curl -L -o liskvork https://cdn.kreog.com/s/Nt7ayTXWctGkn6i/download/liskvork

      - name: add permission
        run: |
          sudo chmod +x liskvork

      - name: Build pbrain-gomoku-ai
        run: |
            make

      - name: Help liskvork
        run: |
            ./liskvork -h
        
      - name: Run ai
        run: |
            ls
            ./liskvork --player1-exe ./build/pbrain-gomoku-ai --player2-exe ./build/pbrain-gomoku-ai --headless --debug-enable || exit_code=$?
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              echo "The game ended in a draw."
              exit 0
            elif [ $exit_code -eq 1 ]; then
              echo "Player1 (GomokuBot) won!"
              exit 0
            elif [ $exit_code -eq 2 ]; then
              echo "Player2 (GomokuBot) won!"
              exit 0
            else
              echo "An error occurred."
              exit $exit_code
            fi
          
